export const REDUX = {
	CLEAR_DATA: 'CLEAR_DATA',

	//USER REDUCER
	LOG_IN: 'LOG_IN',
	LOG_OUT: 'LOG_OUT',
	GET_USER_INFO: 'GET_USER_INFO',

	//CART REDUCER
	ADD_TO_CART: 'ADD_TO_CART',
	REMOVE_FROM_CART: 'REMOVE_FROM_CART',
	UPDATE_ITEM: 'UPDATE_ITEM',
	CLEAR_CART: 'CLEAR_CART',

	//FAVORITE REDUCER
	ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
	REMOVE_FROM_FAVORITE: 'REMOVE_FROM_FAVORITE',
	//SHOP REDUCER
	UPDATE_SHOP_DATA: 'UPDATE_SHOP_DATA',
	CLEAR_SHOP_DATA: 'CLEAR_SHOP_DATA',
	UPDATE_SMART_PHONE_DATA: 'UPDATE_SMART_PHONE_DATA',
	UPDATE_LAPTOP_DATA: 'UPDATE_LAPTOP_DATA',
	UPDATE_TABLET_DATA: 'UPDATE_TABLET_DATA',
	UPDATE_ACCESSORIES_DATA: 'UPDATE_ACCESSORIES_DATA',
	
};
